### ISSUE TITLE
Project and eco-system migration to a post Typescript 2.0 world

### ISSUE THREAD

**Issue by cantide5ga** [typings/discussions#33]
I have a handful of type definitions (some converted from DT) that embrace the use of external modules that was a huge selling point when typings got started.  I'm starting a new project and this is my first opportunity to get in sync with Typings 2.0's support for installing type definitions.  I spent a fair amount of time getting caught up on everything, but everything is still a bit disjointed.  I got some questions/musings:

- Microsoft docs suggest installation via something like `npm install @types/react`, which pulls a migrated definition from the old DefinetlyTyped.  With typings, `typings/registry` was the preferred repo.  
    - I feel like this is a step backwards to potentially using deprecated type definitions.  
    - What steps do I need to take to ensure a type definition from `typings/registry` takes precedence over what `@types` is using?  Especially considering that a handful of PR's to fix/update some definitions only had the registry definitions in mind - not those in DefinetlyTyped
- Are there caveats to installing from `typings/registry` with Typescript 2?  Btw, how would I do that now?
- What exactly is the use case for Typings and the registry now?  Should I continue maintaining here?

I'm very patient and excited to see this all become 'standardized' in a way; I have no strong opinions and am along for the ride :)  but, it's always been a bit painful.  Thanks for any thoughts.

**Comment by blakeembrey** [comment]
1. We're waiting for https://github.com/Microsoft/types-publisher/issues/4 so you can use `@types` with definitions from our registry. You should just be able to continue using Typings or TypeScript 2.0 as is without any issue.
2. Nope, I continue to use exclusively Typings myself because DefinitelyTyped does not contain the definitions I use nor the updates I need.
3. It serves the same purpose as always, and will probably continue to do so for some time. Eventually, I'd like to deprecate it entirely for TypeScript 2.0 native features, but the issue above is blocking that.

There's also https://github.com/typings/typings/issues/600 which you may be interested in.
