### ISSUE TITLE
Typings install gives 502 

### ISSUE THREAD

**Issue by akashpatelj09** [typings/discussions#34]
i am trying to install  typings using script command in npm : typings install && typings prune

I get the following error:
https://api.typings.org/entries/dt/core-js/tags/0.0.0%2B20160914114559 responded with 502, expected it to equal 200

Things i have tried is
1) resetting the http and https proxy 
2) setting strict ssl to false
3) using .typingssrc file this file contains  
{
  "proxy": "http://proxy:8080",
  "defaultSource": "dt"
}

Even then i am getting the above error, i suspect it is a proxy issue. Can someone please help me resolve this

**Comment by demurgos** [comment]
I confirm that the URL works: this is not a server issue but a proxy issue.
I don't know enough about it to help you. We are also missing information about your environment (OS, node, typings, etc.)

As a side note, Typings is deprecated in favor of `@types` and DefinitelyTyped. (But solving your issue is still a valid use case, for example for legacy projects).

**Comment by akashpatelj09** [comment]
Yes it was a proxy issue, we can close this one
